---
- name: Install common runtime dependencies based on OS
  package:
    name: "{{ common_runtime_packages }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Install common runtime dependencies for RHEL-based systems
  package:
    name: "{{ common_runtime_packages_rhel }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Create container storage directory
  file:
    path: "{{ container_storage_path }}"
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Set kernel parameters for containers
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'vm.overcommit_memory', value: '1' }
    - { name: 'kernel.panic', value: '10' }
    - { name: 'kernel.panic_on_oops', value: '1' }

- name: Load required kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  
- name: Ensure kernel modules are loaded at boot
  lineinfile:
    path: /etc/modules-load.d/containerd.conf
    line: "{{ item }}"
    create: yes
  loop:
    - overlay
    - br_netfilter

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap entry from /etc/fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*\s+swap\s+.*$'
    state: absent

- name: Check if zswap is enabled (Fedora)
  command: cat /sys/module/zswap/parameters/enabled
  register: zswap_status
  failed_when: false
  changed_when: false
  when: ansible_distribution == "Fedora"

- name: Disable zswap (Fedora)
  shell: echo 0 > /sys/module/zswap/parameters/enabled
  when: 
    - ansible_distribution == "Fedora"
    - zswap_status.rc == 0
    - zswap_status.stdout == "Y"

- name: Disable zswap permanently via kernel parameters (Fedora)
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="zswap.enabled=0 {{ grub_cmdline_linux | default("") }}"'
    backup: yes
  when: ansible_distribution == "Fedora"
  notify: update grub

- name: Download and install Go for source builds
  block:
    - name: Download Go binary
      get_url:
        url: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /tmp/go{{ go_version }}.tar.gz
        mode: '0644'

    - name: Remove existing Go installation
      file:
        path: /usr/local/go
        state: absent

    - name: Extract Go binary
      unarchive:
        src: /tmp/go{{ go_version }}.tar.gz
        dest: /usr/local
        remote_src: yes
        owner: root
        group: root
  when: containerd_build_method == "source" or crio_build_method == "source"

- name: Create container runtime directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /etc/containers
    - /etc/systemd/system/kubelet.service.d
    - /var/lib/kubelet