#SPDX-License-Identifier: MIT-0
---
# handlers file for runtime

- name: restart containerd
  systemd:
    name: containerd
    state: restarted
    daemon_reload: yes

- name: restart crio
  systemd:
    name: crio
    state: restarted
    daemon_reload: yes

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes

- name: restart podman
  systemd:
    name: podman
    state: restarted
    daemon_reload: yes

- name: update grub
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: ansible_distribution == "Fedora"
